'use strict';
try{
const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9edde);scene.fog=new THREE.Fog(0xe9edde,42,100);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,160);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;
renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','مجسم الحساس ثلاثي الأبعاد. اسحب أو استخدم الأسهم لتدوير المشهد.');document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x9a9e78,1.05));const sun=new THREE.DirectionalLight(0xfff8e4,.8);sun.position.set(-12,25,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20});scene.add(sun);
const material=(c,o=1)=>new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:.05,transparent:o<1,opacity:o,side:THREE.DoubleSide});
const soil=new THREE.Mesh(new THREE.BoxGeometry(24,1.3,21),material(0xc1b38c));soil.position.y=-.66;soil.receiveShadow=true;scene.add(soil);
const edge=new THREE.LineSegments(new THREE.EdgesGeometry(soil.geometry),new THREE.LineBasicMaterial({color:0xaaa57d,transparent:true,opacity:.4}));edge.position.copy(soil.position);scene.add(edge);
const field=new THREE.Group();for(let z=-9;z<=9;z+=1.25){const ridge=new THREE.Mesh(new THREE.BoxGeometry(23,.08,.28),material(0xaeb68b));ridge.position.set(0,.03,z);ridge.receiveShadow=true;field.add(ridge);for(let x=-10;x<11;x+=1.2){if(Math.abs(x)<2.5&&Math.abs(z)<2.5)continue;const sprout=new THREE.Mesh(new THREE.ConeGeometry(.09,.42,4),material(0x789362));sprout.position.set(x,.25,z);field.add(sprout);}}scene.add(field);
const footprint=new THREE.Mesh(new THREE.RingGeometry(6.2,6.26,96),new THREE.MeshBasicMaterial({color:0x5b8452,transparent:true,opacity:.35,side:THREE.DoubleSide}));footprint.rotation.x=-Math.PI/2;footprint.position.y=.10;scene.add(footprint);
const station=new THREE.Group();scene.add(station);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.10,.15,4.2,20),material(0x819384));pole.position.y=2.1;pole.castShadow=true;station.add(pole);
const foot=new THREE.Mesh(new THREE.CylinderGeometry(.47,.7,.12,32),material(0x657f67));foot.position.y=.11;station.add(foot);
const shells=[['aerogel',1.06,0xd8e7b9,.35],['mantle',.92,0x588564,1],['hdpe',.86,0xc5cfc4,1],['cavity',.68,0xdfebd7,.18],['wall',.30,0x94a79b,1],['b4c',.25,0x354e3e,1],['gas',.20,0xdbb56c,.95]];const meshes={};
shells.forEach(([name,radius,color,opacity],i)=>{const geo=new THREE.CylinderGeometry(radius,radius,3.5+(i===0?.15:0),64,1,true,Math.PI*.35,Math.PI*1.55);const mesh=new THREE.Mesh(geo,material(color,opacity));mesh.position.y=5.3;mesh.castShadow=true;station.add(mesh);meshes[name]=mesh;const cap=new THREE.Mesh(new THREE.RingGeometry(Math.max(.05,radius-.045),radius,64,1,Math.PI*.35,Math.PI*1.55),material(color,opacity));cap.rotation.x=-Math.PI/2;cap.position.y=7.07;station.add(cap);});
const solar=new THREE.Group();const solarFrame=new THREE.Mesh(new THREE.BoxGeometry(2.3,.10,1.65),material(0x697d6b));solar.add(solarFrame);const solarFace=new THREE.Mesh(new THREE.BoxGeometry(2.12,.025,1.47),material(0x334f52));solarFace.position.y=.07;solar.add(solarFace);for(let i=-.7;i<=.8;i+=.35){const strip=new THREE.Mesh(new THREE.BoxGeometry(.015,.01,1.4),material(0x89a1a1));strip.position.set(i,.092,0);solar.add(strip);}for(let i=-.5;i<=.6;i+=.35){const strip=new THREE.Mesh(new THREE.BoxGeometry(2.08,.01,.015),material(0x89a1a1));strip.position.set(0,.092,i);solar.add(strip);}solar.rotation.z=-.4;solar.position.set(1.5,3.4,0);station.add(solar);const arm=new THREE.Mesh(new THREE.BoxGeometry(1.5,.08,.08),material(0x7f9681));arm.position.set(.75,3.2,0);station.add(arm);
const particles=[];const pgeo=new THREE.SphereGeometry(.055,6,6);for(let i=0;i<95;i++){const mesh=new THREE.Mesh(pgeo,new THREE.MeshBasicMaterial({color:i%3?0xc8a651:0x7da3a0}));const x=(Math.random()-.5)*19,z=(Math.random()-.5)*16;const up=i%3===0;mesh.position.set(x,Math.random()*15,z);particles.push({mesh,up,speed:.8+Math.random()*2});scene.add(mesh);}
let yaw=.7,pitch=.40,distance=30,drag=false,px=0,py=0,moving=!matchMedia('(prefers-reduced-motion: reduce)').matches;
function place(){camera.position.set(distance*Math.cos(pitch)*Math.sin(yaw),distance*Math.sin(pitch)+2,distance*Math.cos(pitch)*Math.cos(yaw));camera.lookAt(0,3,0);}place();
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.focus()});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('pointercancel',()=>drag=false);renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-px)*.007;pitch=Math.max(.15,Math.min(1.2,pitch+(e.clientY-py)*.006));px=e.clientX;py=e.clientY;place()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(14,Math.min(48,distance+e.deltaY*.025));place()},{passive:false});renderer.domElement.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.12;if(e.key==='ArrowRight')yaw+=.12;if(e.key==='ArrowUp')pitch=Math.min(1.2,pitch+.08);if(e.key==='ArrowDown')pitch=Math.max(.15,pitch-.08);if(['+','='].includes(e.key))distance=Math.max(14,distance-2);if(e.key==='-')distance=Math.min(48,distance+2);place();});
function motionLabel(){document.getElementById('motion').textContent=moving?'إيقاف الحركة':'تشغيل الحركة';document.getElementById('motion').setAttribute('aria-pressed',String(moving));}motionLabel();document.getElementById('motion').onclick=()=>{moving=!moving;motionLabel()};document.getElementById('reset').onclick=()=>{yaw=.7;pitch=.4;distance=30;place()};
const labels={aerogel:'الأيروجيل الكاره للماء',mantle:'عباءة Gd₂O₃',hdpe:'جدار HDPE',cavity:'التجويف الهوائي',wall:'جدار الأنبوب',b4c:'طلاء ¹⁰B₄C',gas:'غاز Ar:CO₂'};
addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='layer')return;const key=e.data.layer;if(key!=='all'&&!meshes[key])return;Object.entries(meshes).forEach(([k,m])=>{const spec=shells.find(s=>s[0]===k);m.material.opacity=key==='all'?spec[3]:k===key?1:.06;m.material.transparent=m.material.opacity<1;m.material.emissive.setHex(k===key?0x304924:0);m.material.emissiveIntensity=.15;m.material.needsUpdate=true;});document.getElementById('layer-name').textContent=labels[key]||'AeroCRNS · Boron-10';});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(moving&&!document.hidden)for(const p of particles){p.mesh.position.y+=dt*p.speed*(p.up?1:-1);if(p.mesh.position.y<.1)p.mesh.position.y=14;if(p.mesh.position.y>14)p.mesh.position.y=.1;}if(!document.hidden)renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
}catch(error){document.body.insertAdjacentHTML('beforeend','<div class="fallback"><strong>تعذّر تشغيل العرض ثلاثي الأبعاد في هذا المتصفح.</strong><p>يمكنك قراءة طبقات الحساس ومواصفاتها في اللوحة المجاورة، أو إعادة فتح المنصة في متصفح يدعم WebGL.</p></div>');}
